// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlfTgftvtH_9n_Yq6-jjIkJ521jyfuMfc',
    appId: '1:331845824773:web:0857f7128db592fb94876c',
    messagingSenderId: '331845824773',
    projectId: 'venta-electrodmtcs',
    authDomain: 'venta-electrodmtcs.firebaseapp.com',
    storageBucket: 'venta-electrodmtcs.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFTeUDug3eTtzLWgIDFHwdbL-3KQX3VxQ',
    appId: '1:331845824773:android:c242323b47db854494876c',
    messagingSenderId: '331845824773',
    projectId: 'venta-electrodmtcs',
    storageBucket: 'venta-electrodmtcs.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKpYAEAQn3YtT65S_6ogbBE_fJn8gCsMQ',
    appId: '1:331845824773:ios:9682bee6980c340494876c',
    messagingSenderId: '331845824773',
    projectId: 'venta-electrodmtcs',
    storageBucket: 'venta-electrodmtcs.appspot.com',
    iosBundleId: 'com.gr1.eltrdm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKpYAEAQn3YtT65S_6ogbBE_fJn8gCsMQ',
    appId: '1:331845824773:ios:0c0a7266bac45ccb94876c',
    messagingSenderId: '331845824773',
    projectId: 'venta-electrodmtcs',
    storageBucket: 'venta-electrodmtcs.appspot.com',
    iosBundleId: 'com.example.prfinal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlfTgftvtH_9n_Yq6-jjIkJ521jyfuMfc',
    appId: '1:331845824773:web:58ea61e125297ab494876c',
    messagingSenderId: '331845824773',
    projectId: 'venta-electrodmtcs',
    authDomain: 'venta-electrodmtcs.firebaseapp.com',
    storageBucket: 'venta-electrodmtcs.appspot.com',
  );
}
